### PR TITLE
Add game end

### PR DESCRIPTION
**Pull request by fenichelar**

### CODE REVIEW

**Comment by BenTheElder** [comment]
Does this actually do what it says? Team 1 should already be green?

**Comment by fenichelar** [comment]
Yes. The pve did team 1 as e not p

**Comment by fenichelar** [comment]
I didn't change the colors of the teams.

**Comment by fenichelar** [comment]
Also green team now has 75% resources. So fleet generator should look at the other team if it can and place based on what the enemy team did.

**Comment by BenTheElder** [comment]
Nice. LGTM

**Pull request merged**
