### PR TITLE
Merge titlescreen state with preload state

### PR DESCRIPTION
**Pull request by fenichelar**

### CODE REVIEW

**Comment by BenTheElder** [comment]
I'm not sure this was a good change, now the user can start the main menu before the game is loaded?

**Comment by fenichelar** [comment]
It can't be started.

**Comment by fenichelar** [comment]
It just is funny right now because nothing is loaded. I added some images and loaded them and it works as expected.

**Comment by BenTheElder** [comment]
Ok. Yeah, I was just working on that: https://gist.github.com/BenTheElder/24065bc77e617ed92fa3c6391d93874a#file-preloader-ts-L30

**Comment by fenichelar** [comment]
The bar also doesn't work correctly because nothing is loaded. It works correctly if 1 or more items are loaded.

**Comment by BenTheElder** [comment]
Worse, it doesn't work correctly if the loaded items are in cache.

**Comment by fenichelar** [comment]
??

**Comment by fenichelar** [comment]
The bar animation only occurs if 1 or more items are loaded. So if nothing is loaded, it never expands out to the fully loaded state. But the text appears as expected.

**Comment by BenTheElder** [comment]
I tested loading some images from phaser's demo site, and if you reload the page and they are already in cache you see the same load bar behavior as if you loaded nothing (ie stuck at just a few px).

I'd just added fading and was looking into forcing the sprite to show in the transition, we could always just display "another sprite" before switching states.

**Comment by fenichelar** [comment]
Resolved by adding another sprite.

**Pull request merged**
